[tool.poetry]
name = "Go to America"
version = "0.1.0"
description = ""
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
langchain = {extras = ["openai"], version = "^1.2.18"}
langchain-openai = "^1.0.1"
langchain-ollama = "^1.0.0"
langgraph = "^1.1.0"
openai = "^1.79.0"
faiss-cpu = "^1.11.0"
duckduckgo-search = "^8.0.2"
beautifulsoup4 = "^4.13.4"
lxml = "^5.4.0"
httpx = "^0.28.1"
pydantic = "^2.11.4"
requests = "^2.33.1"
langchain-text-splitters = "^1.1.2"
deepagents = "^0.5.8"
python-dotenv = "^1.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"