"""
core/pdf_generator.py — Business Plan PDF Generator
=====================================================
Menghasilkan dokumen rencana bisnis profesional dalam format PDF
berdasarkan data dari seluruh agen yang telah selesai berjalan.
"""

import logging
from datetime import datetime
from io import BytesIO
from typing import Optional

logger = logging.getLogger(__name__)


def generate_business_plan_pdf(memory) -> bytes:
    """
    Kumpulkan semua data agen dari SharedMemory dan hasilkan PDF rencana bisnis.
    Return: bytes PDF siap download.
    """
    from fpdf import FPDF, XPos, YPos
    from core.shared_memory import AgentKey
    from core.schemas import (
        InquisitorOutput, OrchestratorReview, CriticOutput, RiskManagerOutput,
        FinanceOutput, MarketOutput, CompetitorOutput, OpsOutput,
        SupplyPlanOutput, HROutput, LegalOutput,
    )

    # ── Ambil semua data ────────────────────────────────────────────────────
    inq     = memory.get(AgentKey.INQUISITOR, InquisitorOutput)
    orc     = memory.get(AgentKey.ORCHESTRATOR, OrchestratorReview)
    critic  = memory.get(AgentKey.CRITIC, CriticOutput)
    risk    = memory.get(AgentKey.RISK_MANAGER, RiskManagerOutput)
    cfo     = memory.get(AgentKey.CFO, FinanceOutput)
    growth  = memory.get(AgentKey.GROWTH_HACKER, MarketOutput)
    ops     = memory.get(AgentKey.PRODUCT_ARCHITECT, OpsOutput)
    supply  = memory.get(AgentKey.SUPPLY_PLANNER, SupplyPlanOutput)
    hr      = memory.get(AgentKey.HR_PLANNER, HROutput)
    legal   = memory.get(AgentKey.LEGAL, LegalOutput)

    ctx = inq.business_context if inq else None
    biz_name = (ctx.business_idea or "Rencana Bisnis Baru") if ctx else "Rencana Bisnis"
    location = ctx.location if ctx else "—"
    sector   = ctx.preferred_sector if ctx else "—"
    budget   = ctx.budget if ctx else 0
    lang     = getattr(ctx, "preferred_language", "id") if ctx else "id"
    is_en    = lang == "en"
    date_str = datetime.now().strftime("%d %B %Y")

    # ── PDF Setup ───────────────────────────────────────────────────────────
    class PDF(FPDF):
        def header(self):
            self.set_font("Helvetica", "B", 9)
            self.set_text_color(120, 120, 120)
            title = "BUSINESS PLAN" if is_en else "RENCANA BISNIS"
            self.cell(0, 8, f"{title} — {biz_name}", align="L", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            self.set_draw_color(200, 200, 200)
            self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
            self.ln(2)

        def footer(self):
            self.set_y(-14)
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(150, 150, 150)
            generated = "Generated by Business Co-Pilot AI"
            self.cell(0, 8, f"{generated} | {date_str} | Page {self.page_no()}", align="C")

    pdf = PDF()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    # ── Helpers ─────────────────────────────────────────────────────────────
    BRAND_COLOR  = (30, 90, 180)   # biru
    ACCENT_COLOR = (60, 140, 100)  # hijau
    WARN_COLOR   = (180, 60, 40)   # merah
    GRAY         = (90, 90, 90)
    LIGHT_GRAY   = (230, 230, 230)

    def section_title(text: str, color=BRAND_COLOR):
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(*color)
        pdf.ln(4)
        pdf.cell(0, 8, text, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_draw_color(*color)
        pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
        pdf.set_text_color(30, 30, 30)
        pdf.ln(3)

    def sub_title(text: str):
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*GRAY)
        pdf.cell(0, 6, text, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_text_color(30, 30, 30)

    def body(text: str, indent: int = 0):
        if not text:
            return
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(40, 40, 40)
        pdf.set_x(pdf.l_margin + indent)
        pdf.multi_cell(pdf.w - pdf.l_margin - pdf.r_margin - indent, 5, _clean(text))
        pdf.ln(1)

    def bullet_list(items, indent: int = 4):
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(40, 40, 40)
        for item in (items or []):
            pdf.set_x(pdf.l_margin + indent)
            pdf.multi_cell(pdf.w - pdf.l_margin - pdf.r_margin - indent, 5, f"\u2022  {_clean(str(item))}")
        pdf.ln(1)

    def kv(key: str, value, bold_val: bool = False):
        """Key: Value row"""
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*GRAY)
        pdf.cell(55, 5, f"{key}:", new_x=XPos.RIGHT, new_y=YPos.SAME)
        pdf.set_font("Helvetica", "B" if bold_val else "", 9)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 5, _clean(str(value)), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    def _clean(text: str) -> str:
        """Hapus karakter non-latin yang tidak bisa dirender Helvetica."""
        result = []
        for ch in str(text):
            if ord(ch) < 128:
                result.append(ch)
            else:
                # Transliterasi karakter Indonesia umum
                _map = {
                    "á":"a","à":"a","â":"a","ä":"a","ã":"a",
                    "é":"e","è":"e","ê":"e","ë":"e",
                    "í":"i","ì":"i","î":"i","ï":"i",
                    "ó":"o","ò":"o","ô":"o","ö":"o","õ":"o",
                    "ú":"u","ù":"u","û":"u","ü":"u",
                    "ñ":"n","ç":"c","Á":"A","É":"E","Í":"I","Ó":"O","Ú":"U","Ñ":"N",
                    "\u2014":"-","\u2013":"-","\u2018":"'","\u2019":"'","\u201c":'"',"\u201d":'"',
                    "\u2022":"*","\u25cf":"*","\u2713":"v","\u274c":"X","\u26a0":"!",
                    "\u2139":"i","\U0001f4a1":"[!]","\U0001f50d":"[*]","\U0001f4ac":"[>]",
                    "Rp":"Rp","—":"-",
                }
                result.append(_map.get(ch, ""))
        return "".join(result)

    def colored_box(text: str, bg: tuple, text_color=(255,255,255)):
        pdf.set_fill_color(*bg)
        pdf.set_text_color(*text_color)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 8, f"  {_clean(text)}", fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_text_color(30, 30, 30)
        pdf.ln(2)

    # ══════════════════════════════════════════════════════════════════════════
    # COVER
    # ══════════════════════════════════════════════════════════════════════════
    pdf.set_y(40)
    pdf.set_font("Helvetica", "B", 24)
    pdf.set_text_color(*BRAND_COLOR)
    cover_title = "BUSINESS PLAN" if is_en else "RENCANA BISNIS"
    pdf.cell(0, 12, cover_title, align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 10, _clean(biz_name), align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.ln(6)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(*GRAY)
    pdf.cell(0, 6, f"Lokasi: {_clean(location)}  |  Sektor: {_clean(sector)}", align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 6, f"Modal Awal: Rp {budget:,.0f}", align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 6, f"Tanggal: {date_str}", align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.ln(10)
    pdf.set_draw_color(*BRAND_COLOR)
    pdf.set_line_width(0.8)
    mid_x = pdf.l_margin + (pdf.w - pdf.l_margin - pdf.r_margin) / 4
    pdf.line(mid_x, pdf.get_y(), pdf.w - mid_x, pdf.get_y())
    pdf.set_line_width(0.2)
    pdf.ln(8)

    # AI generated badge
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 6, "Generated by Business Co-Pilot AI | Powered by Multi-Agent Research", align="C",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # Status keputusan
    if orc:
        pdf.ln(8)
        if orc.approved:
            colored_box("  STATUS: LAYAK DIEKSEKUSI", ACCENT_COLOR)
        else:
            colored_box("  STATUS: PERLU PENYEMPURNAAN", WARN_COLOR)

    # ══════════════════════════════════════════════════════════════════════════
    # SECTION 1: RINGKASAN EKSEKUTIF
    # ══════════════════════════════════════════════════════════════════════════
    pdf.add_page()
    section_title("1. RINGKASAN EKSEKUTIF")
    if orc:
        body(orc.executive_summary)
        pdf.ln(2)
        sub_title("Rekomendasi Final:")
        body(orc.final_recommendation, indent=4)
        if orc.next_steps:
            pdf.ln(2)
            sub_title("Langkah Selanjutnya:")
            bullet_list(orc.next_steps, indent=4)

    # ══════════════════════════════════════════════════════════════════════════
    # SECTION 2: PROFIL BISNIS
    # ══════════════════════════════════════════════════════════════════════════
    section_title("2. PROFIL BISNIS")
    if ctx:
        kv("Ide Bisnis", ctx.business_idea or "—")
        kv("Lokasi", ctx.location)
        kv("Sektor", ctx.preferred_sector or "—")
        kv("Modal Awal", f"Rp {ctx.budget:,.0f}", bold_val=True)
        if ctx.target_monthly_income:
            kv("Target Pendapatan/Bln", f"Rp {ctx.target_monthly_income:,.0f}")
        if ctx.skills:
            kv("Keahlian Pemilik", ", ".join(ctx.skills))
        if ctx.existing_assets:
            kv("Aset yang Dimiliki", ", ".join(ctx.existing_assets))

    # ══════════════════════════════════════════════════════════════════════════
    # SECTION 3: ANALISIS PASAR
    # ══════════════════════════════════════════════════════════════════════════
    section_title("3. ANALISIS PASAR & PELUANG")
    if growth:
        sub_title("Ringkasan Pasar:")
        body(getattr(growth, "market_summary", None) or getattr(growth, "recommended_idea", "—"))
        kv("Target Segmen", getattr(growth, "target_segment", "—"))
        kv("Value Proposition", getattr(growth, "value_proposition", "—"))
        if hasattr(growth, "growth_strategies") and growth.growth_strategies:
            sub_title("Strategi Pertumbuhan:")
            bullet_list(growth.growth_strategies)
    else:
        body("Data analisis pasar tidak tersedia.")

    # ══════════════════════════════════════════════════════════════════════════
    # SECTION 4: PROYEKSI KEUANGAN
    # ══════════════════════════════════════════════════════════════════════════
    section_title("4. PROYEKSI KEUANGAN")
    if cfo:
        kv("Total Modal Awal", f"Rp {cfo.recommended_capital:,.0f}", bold_val=True)
        kv("Total Biaya Bulanan", f"Rp {cfo.total_monthly_cost:,.0f}")
        kv("Proyeksi Pendapatan/Bln", f"Rp {cfo.projected_monthly_revenue:,.0f}")
        kv("Proyeksi Laba Bersih (Bln 6)", f"Rp {cfo.projected_net_profit_month6:,.0f}")
        kv("Break Even (BEP)", f"{cfo.bep_months:.1f} bulan", bold_val=True)
        kv("Risk Level Keuangan", cfo.risk_level.upper())
        if cfo.startup_cost:
            pdf.ln(2)
            sub_title("Rincian Biaya Awal (Startup Cost):")
            for item in cfo.startup_cost:
                label = item.get("item", item.get("name", "—"))
                amount = item.get("amount", item.get("cost", 0))
                pdf.set_font("Helvetica", "", 9)
                pdf.set_x(pdf.l_margin + 4)
                pdf.cell(90, 5, f"\u2022  {_clean(str(label))}", new_x=XPos.RIGHT, new_y=YPos.SAME)
                pdf.cell(0, 5, f"Rp {float(amount):,.0f}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        if cfo.monthly_cost:
            pdf.ln(2)
            sub_title("Rincian Biaya Operasional Bulanan:")
            for item in cfo.monthly_cost:
                label = item.get("item", item.get("name", "—"))
                amount = item.get("amount", item.get("cost", 0))
                pdf.set_font("Helvetica", "", 9)
                pdf.set_x(pdf.l_margin + 4)
                pdf.cell(90, 5, f"\u2022  {_clean(str(label))}", new_x=XPos.RIGHT, new_y=YPos.SAME)
                pdf.cell(0, 5, f"Rp {float(amount):,.0f}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    else:
        body("Data proyeksi keuangan tidak tersedia.")

    # ══════════════════════════════════════════════════════════════════════════
    # SECTION 5: RENCANA OPERASIONAL
    # ══════════════════════════════════════════════════════════════════════════
    section_title("5. RENCANA OPERASIONAL")
    if ops:
        kv("Kapasitas Harian", f"{ops.daily_capacity} unit/hari")
        kv("Staff Minimum", f"{ops.minimum_staff} orang")
        kv("Total Biaya Peralatan", f"Rp {ops.total_equipment_cost:,.0f}")
        if ops.equipment_list:
            pdf.ln(2)
            sub_title("Daftar Peralatan:")
            for eq in ops.equipment_list:
                name = eq.name if hasattr(eq, "name") else eq.get("name", "—")
                qty  = eq.quantity if hasattr(eq, "quantity") else eq.get("quantity", 1)
                cost = eq.estimated_cost if hasattr(eq, "estimated_cost") else eq.get("estimated_cost", 0)
                pdf.set_font("Helvetica", "", 9)
                pdf.set_x(pdf.l_margin + 4)
                pdf.cell(80, 5, f"\u2022  {_clean(str(name))} (x{qty})", new_x=XPos.RIGHT, new_y=YPos.SAME)
                pdf.cell(0, 5, f"Rp {float(cost):,.0f}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        if ops.operational_flow:
            pdf.ln(2)
            sub_title("Alur Operasional Harian:")
            for j, step in enumerate(ops.operational_flow, 1):
                pdf.set_font("Helvetica", "", 9)
                pdf.set_x(pdf.l_margin + 4)
                pdf.multi_cell(pdf.w - pdf.l_margin - pdf.r_margin - 4, 5, f"{j}. {_clean(str(step))}")
    else:
        body("Data rencana operasional tidak tersedia.")

    # ══════════════════════════════════════════════════════════════════════════
    # SECTION 6: SUPPLY CHAIN & HPP
    # ══════════════════════════════════════════════════════════════════════════
    section_title("6. SUPPLY CHAIN & HPP")
    if supply:
        kv("HPP per Unit", f"Rp {supply.hpp_per_unit:,.2f}", bold_val=True)
        kv("COGS Harian", f"Rp {supply.daily_cogs:,.0f}")
        kv("COGS Bulanan", f"Rp {supply.monthly_cogs:,.0f}")
        if supply.supplier_recommendations:
            pdf.ln(2)
            sub_title("Rekomendasi Supplier:")
            bullet_list(supply.supplier_recommendations)
    else:
        body("Data supply chain tidak tersedia.")

    # ══════════════════════════════════════════════════════════════════════════
    # SECTION 7: PERENCANAAN SDM
    # ══════════════════════════════════════════════════════════════════════════
    section_title("7. PERENCANAAN SDM")
    if hr:
        kv("Total Staf", f"{getattr(hr, 'total_staff', '—')} orang")
        kv("Total Gaji Bulanan", f"Rp {getattr(hr, 'total_monthly_salary', 0):,.0f}")
        if hasattr(hr, "staff_plan") and hr.staff_plan:
            pdf.ln(2)
            sub_title("Rencana Staf:")
            for staff in hr.staff_plan:
                role   = staff.get("role", staff.get("position", "—"))
                count  = staff.get("count", staff.get("quantity", 1))
                salary = staff.get("salary", staff.get("monthly_salary", 0))
                pdf.set_font("Helvetica", "", 9)
                pdf.set_x(pdf.l_margin + 4)
                pdf.cell(80, 5, f"\u2022  {_clean(str(role))} (x{count})", new_x=XPos.RIGHT, new_y=YPos.SAME)
                pdf.cell(0, 5, f"Rp {float(salary):,.0f}/bln", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    else:
        body("Data perencanaan SDM tidak tersedia.")

    # ══════════════════════════════════════════════════════════════════════════
    # SECTION 8: ASPEK HUKUM & PERIZINAN
    # ══════════════════════════════════════════════════════════════════════════
    section_title("8. ASPEK HUKUM & PERIZINAN")
    if legal:
        if hasattr(legal, "required_licenses") and legal.required_licenses:
            sub_title("Perizinan yang Diperlukan:")
            bullet_list(legal.required_licenses)
        if hasattr(legal, "business_entity") and legal.business_entity:
            kv("Bentuk Usaha", legal.business_entity)
        if hasattr(legal, "estimated_legal_cost") and legal.estimated_legal_cost:
            kv("Estimasi Biaya Legal", f"Rp {legal.estimated_legal_cost:,.0f}")
        if hasattr(legal, "compliance_notes") and legal.compliance_notes:
            sub_title("Catatan Kepatuhan:")
            body(legal.compliance_notes, indent=4)
    else:
        body("Data aspek hukum tidak tersedia.")

    # ══════════════════════════════════════════════════════════════════════════
    # SECTION 9: ANALISIS RISIKO
    # ══════════════════════════════════════════════════════════════════════════
    section_title("9. ANALISIS RISIKO")
    if risk:
        kv("Viabilitas Rencana", risk.overall_viability, bold_val=True)
        sub_title("Skenario Terbaik:")
        body(risk.best_case_summary, indent=4)
        sub_title("Skenario Terburuk:")
        body(risk.worst_case_summary, indent=4)
        if hasattr(risk, "mitigation_strategies") and risk.mitigation_strategies:
            sub_title("Strategi Mitigasi:")
            bullet_list(risk.mitigation_strategies)
    else:
        body("Data analisis risiko tidak tersedia.")

    # ══════════════════════════════════════════════════════════════════════════
    # SECTION 10: EVALUASI & KEPUTUSAN AKHIR
    # ══════════════════════════════════════════════════════════════════════════
    section_title("10. EVALUASI & KEPUTUSAN AKHIR")
    if critic:
        kv("Risk Level (Critic)", critic.overall_risk_level.upper())
        kv("Jumlah Isu Kritis", str(critic.critical_count))
        kv("Perlu Revisi", "Ya" if critic.revision_required else "Tidak")
        if critic.issues_found:
            pdf.ln(2)
            sub_title("Temuan Evaluasi:")
            for iss in critic.issues_found:
                sev  = str(iss.severity).upper()
                desc = _clean(iss.description)
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_x(pdf.l_margin + 4)
                pdf.cell(0, 5, f"[{sev}] {_clean(iss.agent_source.upper())}:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.set_font("Helvetica", "", 9)
                pdf.set_x(pdf.l_margin + 8)
                pdf.multi_cell(pdf.w - pdf.l_margin - pdf.r_margin - 8, 5, desc)
                pdf.ln(1)

    if orc:
        pdf.ln(2)
        verdict_color = ACCENT_COLOR if orc.approved else WARN_COLOR
        verdict_text  = "LAYAK DIEKSEKUSI" if orc.approved else "PERLU PENYEMPURNAAN"
        colored_box(f"KEPUTUSAN AKHIR: {verdict_text}", verdict_color)
        reasoning = getattr(orc, "reasoning", None)
        if reasoning:
            sub_title("Alur Pemikiran CEO:")
            body(reasoning, indent=4)

    # ── Render ke bytes ──────────────────────────────────────────────────────
    buf = BytesIO()
    pdf_bytes = pdf.output()
    return bytes(pdf_bytes)
